//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18063
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace STK_Client.Ref_WS_STK {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelBase", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_Role))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_Param))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_Grid))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_仓库))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_存货))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_存货_类别))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_库存管理))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_供应商))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_会计期间))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_库存分布))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(STK_Client.Ref_WS_STK.DataType_User))]
    public partial class ModelBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Date_EField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ExActionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ExResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginUserPswdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageCountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageIndexField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int PageRowsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowsCountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_B {
            get {
                return this.Date_BField;
            }
            set {
                if ((this.Date_BField.Equals(value) != true)) {
                    this.Date_BField = value;
                    this.RaisePropertyChanged("Date_B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date_E {
            get {
                return this.Date_EField;
            }
            set {
                if ((this.Date_EField.Equals(value) != true)) {
                    this.Date_EField = value;
                    this.RaisePropertyChanged("Date_E");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExAction {
            get {
                return this.ExActionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExActionField, value) != true)) {
                    this.ExActionField = value;
                    this.RaisePropertyChanged("ExAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExResult {
            get {
                return this.ExResultField;
            }
            set {
                if ((this.ExResultField.Equals(value) != true)) {
                    this.ExResultField = value;
                    this.RaisePropertyChanged("ExResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginUserCode {
            get {
                return this.LoginUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginUserCodeField, value) != true)) {
                    this.LoginUserCodeField = value;
                    this.RaisePropertyChanged("LoginUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginUserPswd {
            get {
                return this.LoginUserPswdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginUserPswdField, value) != true)) {
                    this.LoginUserPswdField = value;
                    this.RaisePropertyChanged("LoginUserPswd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageCount {
            get {
                return this.PageCountField;
            }
            set {
                if ((this.PageCountField.Equals(value) != true)) {
                    this.PageCountField = value;
                    this.RaisePropertyChanged("PageCount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageIndex {
            get {
                return this.PageIndexField;
            }
            set {
                if ((this.PageIndexField.Equals(value) != true)) {
                    this.PageIndexField = value;
                    this.RaisePropertyChanged("PageIndex");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PageRows {
            get {
                return this.PageRowsField;
            }
            set {
                if ((this.PageRowsField.Equals(value) != true)) {
                    this.PageRowsField = value;
                    this.RaisePropertyChanged("PageRows");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowsCount {
            get {
                return this.RowsCountField;
            }
            set {
                if ((this.RowsCountField.Equals(value) != true)) {
                    this.RowsCountField = value;
                    this.RaisePropertyChanged("RowsCount");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_Role", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_Role : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RoleIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleMenuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RoleID {
            get {
                return this.RoleIDField;
            }
            set {
                if ((this.RoleIDField.Equals(value) != true)) {
                    this.RoleIDField = value;
                    this.RaisePropertyChanged("RoleID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleMemo {
            get {
                return this.RoleMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleMemoField, value) != true)) {
                    this.RoleMemoField = value;
                    this.RaisePropertyChanged("RoleMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleMenu {
            get {
                return this.RoleMenuField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleMenuField, value) != true)) {
                    this.RoleMenuField = value;
                    this.RaisePropertyChanged("RoleMenu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleName {
            get {
                return this.RoleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleNameField, value) != true)) {
                    this.RoleNameField = value;
                    this.RaisePropertyChanged("RoleName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_Param", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_Param : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CSVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DBVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DP_MoneyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DP_NumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WSVersionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 公司传真Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 公司名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 公司地址Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 公司电话Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 公司负责人Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CSVersion {
            get {
                return this.CSVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.CSVersionField, value) != true)) {
                    this.CSVersionField = value;
                    this.RaisePropertyChanged("CSVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DBVersion {
            get {
                return this.DBVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.DBVersionField, value) != true)) {
                    this.DBVersionField = value;
                    this.RaisePropertyChanged("DBVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DP_Money {
            get {
                return this.DP_MoneyField;
            }
            set {
                if ((this.DP_MoneyField.Equals(value) != true)) {
                    this.DP_MoneyField = value;
                    this.RaisePropertyChanged("DP_Money");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int DP_Number {
            get {
                return this.DP_NumberField;
            }
            set {
                if ((this.DP_NumberField.Equals(value) != true)) {
                    this.DP_NumberField = value;
                    this.RaisePropertyChanged("DP_Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WSVersion {
            get {
                return this.WSVersionField;
            }
            set {
                if ((object.ReferenceEquals(this.WSVersionField, value) != true)) {
                    this.WSVersionField = value;
                    this.RaisePropertyChanged("WSVersion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 公司传真 {
            get {
                return this.公司传真Field;
            }
            set {
                if ((object.ReferenceEquals(this.公司传真Field, value) != true)) {
                    this.公司传真Field = value;
                    this.RaisePropertyChanged("公司传真");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 公司名称 {
            get {
                return this.公司名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.公司名称Field, value) != true)) {
                    this.公司名称Field = value;
                    this.RaisePropertyChanged("公司名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 公司地址 {
            get {
                return this.公司地址Field;
            }
            set {
                if ((object.ReferenceEquals(this.公司地址Field, value) != true)) {
                    this.公司地址Field = value;
                    this.RaisePropertyChanged("公司地址");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 公司电话 {
            get {
                return this.公司电话Field;
            }
            set {
                if ((object.ReferenceEquals(this.公司电话Field, value) != true)) {
                    this.公司电话Field = value;
                    this.RaisePropertyChanged("公司电话");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 公司负责人 {
            get {
                return this.公司负责人Field;
            }
            set {
                if ((object.ReferenceEquals(this.公司负责人Field, value) != true)) {
                    this.公司负责人Field = value;
                    this.RaisePropertyChanged("公司负责人");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_Grid", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_Grid : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridDefineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridMemoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GridUserField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GridDefine {
            get {
                return this.GridDefineField;
            }
            set {
                if ((object.ReferenceEquals(this.GridDefineField, value) != true)) {
                    this.GridDefineField = value;
                    this.RaisePropertyChanged("GridDefine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GridMemo {
            get {
                return this.GridMemoField;
            }
            set {
                if ((object.ReferenceEquals(this.GridMemoField, value) != true)) {
                    this.GridMemoField = value;
                    this.RaisePropertyChanged("GridMemo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GridName {
            get {
                return this.GridNameField;
            }
            set {
                if ((object.ReferenceEquals(this.GridNameField, value) != true)) {
                    this.GridNameField = value;
                    this.RaisePropertyChanged("GridName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GridUser {
            get {
                return this.GridUserField;
            }
            set {
                if ((object.ReferenceEquals(this.GridUserField, value) != true)) {
                    this.GridUserField = value;
                    this.RaisePropertyChanged("GridUser");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_仓库", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_仓库 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MxDataXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 上级编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库位置编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库地址Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 仓库容量Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 仓库状态Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库电话Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 仓库类型Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库负责人Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 创建人编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 创建时间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 包含所有项Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 备注Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MxDataXML {
            get {
                return this.MxDataXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.MxDataXMLField, value) != true)) {
                    this.MxDataXMLField = value;
                    this.RaisePropertyChanged("MxDataXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 上级编码 {
            get {
                return this.上级编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.上级编码Field, value) != true)) {
                    this.上级编码Field = value;
                    this.RaisePropertyChanged("上级编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库位置编码 {
            get {
                return this.仓库位置编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库位置编码Field, value) != true)) {
                    this.仓库位置编码Field = value;
                    this.RaisePropertyChanged("仓库位置编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库名称 {
            get {
                return this.仓库名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库名称Field, value) != true)) {
                    this.仓库名称Field = value;
                    this.RaisePropertyChanged("仓库名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库地址 {
            get {
                return this.仓库地址Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库地址Field, value) != true)) {
                    this.仓库地址Field = value;
                    this.RaisePropertyChanged("仓库地址");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 仓库容量 {
            get {
                return this.仓库容量Field;
            }
            set {
                if ((this.仓库容量Field.Equals(value) != true)) {
                    this.仓库容量Field = value;
                    this.RaisePropertyChanged("仓库容量");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 仓库状态 {
            get {
                return this.仓库状态Field;
            }
            set {
                if ((this.仓库状态Field.Equals(value) != true)) {
                    this.仓库状态Field = value;
                    this.RaisePropertyChanged("仓库状态");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库电话 {
            get {
                return this.仓库电话Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库电话Field, value) != true)) {
                    this.仓库电话Field = value;
                    this.RaisePropertyChanged("仓库电话");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 仓库类型 {
            get {
                return this.仓库类型Field;
            }
            set {
                if ((this.仓库类型Field.Equals(value) != true)) {
                    this.仓库类型Field = value;
                    this.RaisePropertyChanged("仓库类型");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库编码 {
            get {
                return this.仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库编码Field, value) != true)) {
                    this.仓库编码Field = value;
                    this.RaisePropertyChanged("仓库编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库负责人 {
            get {
                return this.仓库负责人Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库负责人Field, value) != true)) {
                    this.仓库负责人Field = value;
                    this.RaisePropertyChanged("仓库负责人");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 创建人编码 {
            get {
                return this.创建人编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.创建人编码Field, value) != true)) {
                    this.创建人编码Field = value;
                    this.RaisePropertyChanged("创建人编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 创建时间 {
            get {
                return this.创建时间Field;
            }
            set {
                if ((this.创建时间Field.Equals(value) != true)) {
                    this.创建时间Field = value;
                    this.RaisePropertyChanged("创建时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 包含所有项 {
            get {
                return this.包含所有项Field;
            }
            set {
                if ((this.包含所有项Field.Equals(value) != true)) {
                    this.包含所有项Field = value;
                    this.RaisePropertyChanged("包含所有项");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注 {
            get {
                return this.备注Field;
            }
            set {
                if ((object.ReferenceEquals(this.备注Field, value) != true)) {
                    this.备注Field = value;
                    this.RaisePropertyChanged("备注");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_存货", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_存货 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 上一个序号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 助记码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 包含下级Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 可出库Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 备注Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 存货单价Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 存货名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 存货状态Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 存货编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 库存上限Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 库存下限Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 类别序号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 类别编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 规格型号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 计量单位Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 默认仓库编码Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 上一个序号 {
            get {
                return this.上一个序号Field;
            }
            set {
                if ((this.上一个序号Field.Equals(value) != true)) {
                    this.上一个序号Field = value;
                    this.RaisePropertyChanged("上一个序号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 助记码 {
            get {
                return this.助记码Field;
            }
            set {
                if ((object.ReferenceEquals(this.助记码Field, value) != true)) {
                    this.助记码Field = value;
                    this.RaisePropertyChanged("助记码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 包含下级 {
            get {
                return this.包含下级Field;
            }
            set {
                if ((this.包含下级Field.Equals(value) != true)) {
                    this.包含下级Field = value;
                    this.RaisePropertyChanged("包含下级");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 可出库 {
            get {
                return this.可出库Field;
            }
            set {
                if ((this.可出库Field.Equals(value) != true)) {
                    this.可出库Field = value;
                    this.RaisePropertyChanged("可出库");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注 {
            get {
                return this.备注Field;
            }
            set {
                if ((object.ReferenceEquals(this.备注Field, value) != true)) {
                    this.备注Field = value;
                    this.RaisePropertyChanged("备注");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 存货单价 {
            get {
                return this.存货单价Field;
            }
            set {
                if ((this.存货单价Field.Equals(value) != true)) {
                    this.存货单价Field = value;
                    this.RaisePropertyChanged("存货单价");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 存货名称 {
            get {
                return this.存货名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.存货名称Field, value) != true)) {
                    this.存货名称Field = value;
                    this.RaisePropertyChanged("存货名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 存货状态 {
            get {
                return this.存货状态Field;
            }
            set {
                if ((this.存货状态Field.Equals(value) != true)) {
                    this.存货状态Field = value;
                    this.RaisePropertyChanged("存货状态");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 存货编码 {
            get {
                return this.存货编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.存货编码Field, value) != true)) {
                    this.存货编码Field = value;
                    this.RaisePropertyChanged("存货编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 库存上限 {
            get {
                return this.库存上限Field;
            }
            set {
                if ((this.库存上限Field.Equals(value) != true)) {
                    this.库存上限Field = value;
                    this.RaisePropertyChanged("库存上限");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 库存下限 {
            get {
                return this.库存下限Field;
            }
            set {
                if ((this.库存下限Field.Equals(value) != true)) {
                    this.库存下限Field = value;
                    this.RaisePropertyChanged("库存下限");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 类别序号 {
            get {
                return this.类别序号Field;
            }
            set {
                if ((this.类别序号Field.Equals(value) != true)) {
                    this.类别序号Field = value;
                    this.RaisePropertyChanged("类别序号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 类别编码 {
            get {
                return this.类别编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.类别编码Field, value) != true)) {
                    this.类别编码Field = value;
                    this.RaisePropertyChanged("类别编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 规格型号 {
            get {
                return this.规格型号Field;
            }
            set {
                if ((object.ReferenceEquals(this.规格型号Field, value) != true)) {
                    this.规格型号Field = value;
                    this.RaisePropertyChanged("规格型号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 计量单位 {
            get {
                return this.计量单位Field;
            }
            set {
                if ((object.ReferenceEquals(this.计量单位Field, value) != true)) {
                    this.计量单位Field = value;
                    this.RaisePropertyChanged("计量单位");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 默认仓库编码 {
            get {
                return this.默认仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.默认仓库编码Field, value) != true)) {
                    this.默认仓库编码Field = value;
                    this.RaisePropertyChanged("默认仓库编码");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_存货_类别", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_存货_类别 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 上级编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 创建人编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 创建时间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 助记词Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 备注Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 类别名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 类别状态Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int 类别类型Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 类别编码Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 上级编码 {
            get {
                return this.上级编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.上级编码Field, value) != true)) {
                    this.上级编码Field = value;
                    this.RaisePropertyChanged("上级编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 创建人编码 {
            get {
                return this.创建人编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.创建人编码Field, value) != true)) {
                    this.创建人编码Field = value;
                    this.RaisePropertyChanged("创建人编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 创建时间 {
            get {
                return this.创建时间Field;
            }
            set {
                if ((this.创建时间Field.Equals(value) != true)) {
                    this.创建时间Field = value;
                    this.RaisePropertyChanged("创建时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 助记词 {
            get {
                return this.助记词Field;
            }
            set {
                if ((object.ReferenceEquals(this.助记词Field, value) != true)) {
                    this.助记词Field = value;
                    this.RaisePropertyChanged("助记词");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注 {
            get {
                return this.备注Field;
            }
            set {
                if ((object.ReferenceEquals(this.备注Field, value) != true)) {
                    this.备注Field = value;
                    this.RaisePropertyChanged("备注");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 类别名称 {
            get {
                return this.类别名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.类别名称Field, value) != true)) {
                    this.类别名称Field = value;
                    this.RaisePropertyChanged("类别名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 类别状态 {
            get {
                return this.类别状态Field;
            }
            set {
                if ((this.类别状态Field.Equals(value) != true)) {
                    this.类别状态Field = value;
                    this.RaisePropertyChanged("类别状态");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int 类别类型 {
            get {
                return this.类别类型Field;
            }
            set {
                if ((this.类别类型Field.Equals(value) != true)) {
                    this.类别类型Field = value;
                    this.RaisePropertyChanged("类别类型");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 类别编码 {
            get {
                return this.类别编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.类别编码Field, value) != true)) {
                    this.类别编码Field = value;
                    this.RaisePropertyChanged("类别编码");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_库存管理", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_库存管理 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MxDataXMLField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 业务日期Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 会计期间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 供应商编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 制单人编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 包含下级Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 单据类型Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 单据编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 原始单号Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 备注Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 存货名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 存货编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 开始时间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 所有未审核Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 期初单价Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 期初数量Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal 期初金额Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 类别编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 结束时间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 货架编码Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MxDataXML {
            get {
                return this.MxDataXMLField;
            }
            set {
                if ((object.ReferenceEquals(this.MxDataXMLField, value) != true)) {
                    this.MxDataXMLField = value;
                    this.RaisePropertyChanged("MxDataXML");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 业务日期 {
            get {
                return this.业务日期Field;
            }
            set {
                if ((this.业务日期Field.Equals(value) != true)) {
                    this.业务日期Field = value;
                    this.RaisePropertyChanged("业务日期");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库编码 {
            get {
                return this.仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库编码Field, value) != true)) {
                    this.仓库编码Field = value;
                    this.RaisePropertyChanged("仓库编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 会计期间 {
            get {
                return this.会计期间Field;
            }
            set {
                if ((object.ReferenceEquals(this.会计期间Field, value) != true)) {
                    this.会计期间Field = value;
                    this.RaisePropertyChanged("会计期间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 供应商编码 {
            get {
                return this.供应商编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.供应商编码Field, value) != true)) {
                    this.供应商编码Field = value;
                    this.RaisePropertyChanged("供应商编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 制单人编码 {
            get {
                return this.制单人编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.制单人编码Field, value) != true)) {
                    this.制单人编码Field = value;
                    this.RaisePropertyChanged("制单人编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 包含下级 {
            get {
                return this.包含下级Field;
            }
            set {
                if ((this.包含下级Field.Equals(value) != true)) {
                    this.包含下级Field = value;
                    this.RaisePropertyChanged("包含下级");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 单据类型 {
            get {
                return this.单据类型Field;
            }
            set {
                if ((object.ReferenceEquals(this.单据类型Field, value) != true)) {
                    this.单据类型Field = value;
                    this.RaisePropertyChanged("单据类型");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 单据编码 {
            get {
                return this.单据编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.单据编码Field, value) != true)) {
                    this.单据编码Field = value;
                    this.RaisePropertyChanged("单据编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 原始单号 {
            get {
                return this.原始单号Field;
            }
            set {
                if ((object.ReferenceEquals(this.原始单号Field, value) != true)) {
                    this.原始单号Field = value;
                    this.RaisePropertyChanged("原始单号");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注 {
            get {
                return this.备注Field;
            }
            set {
                if ((object.ReferenceEquals(this.备注Field, value) != true)) {
                    this.备注Field = value;
                    this.RaisePropertyChanged("备注");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 存货名称 {
            get {
                return this.存货名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.存货名称Field, value) != true)) {
                    this.存货名称Field = value;
                    this.RaisePropertyChanged("存货名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 存货编码 {
            get {
                return this.存货编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.存货编码Field, value) != true)) {
                    this.存货编码Field = value;
                    this.RaisePropertyChanged("存货编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 开始时间 {
            get {
                return this.开始时间Field;
            }
            set {
                if ((this.开始时间Field.Equals(value) != true)) {
                    this.开始时间Field = value;
                    this.RaisePropertyChanged("开始时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 所有未审核 {
            get {
                return this.所有未审核Field;
            }
            set {
                if ((this.所有未审核Field.Equals(value) != true)) {
                    this.所有未审核Field = value;
                    this.RaisePropertyChanged("所有未审核");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 期初单价 {
            get {
                return this.期初单价Field;
            }
            set {
                if ((this.期初单价Field.Equals(value) != true)) {
                    this.期初单价Field = value;
                    this.RaisePropertyChanged("期初单价");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 期初数量 {
            get {
                return this.期初数量Field;
            }
            set {
                if ((this.期初数量Field.Equals(value) != true)) {
                    this.期初数量Field = value;
                    this.RaisePropertyChanged("期初数量");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal 期初金额 {
            get {
                return this.期初金额Field;
            }
            set {
                if ((this.期初金额Field.Equals(value) != true)) {
                    this.期初金额Field = value;
                    this.RaisePropertyChanged("期初金额");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 类别编码 {
            get {
                return this.类别编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.类别编码Field, value) != true)) {
                    this.类别编码Field = value;
                    this.RaisePropertyChanged("类别编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 结束时间 {
            get {
                return this.结束时间Field;
            }
            set {
                if ((this.结束时间Field.Equals(value) != true)) {
                    this.结束时间Field = value;
                    this.RaisePropertyChanged("结束时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 货架编码 {
            get {
                return this.货架编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.货架编码Field, value) != true)) {
                    this.货架编码Field = value;
                    this.RaisePropertyChanged("货架编码");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_供应商", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_供应商 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 业务范围Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 传真Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 供应商名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 供应商编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 地址Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 备注Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 开户银行Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 电话Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 联系人Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 联系人手机Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 邮编Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 银行账号Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 业务范围 {
            get {
                return this.业务范围Field;
            }
            set {
                if ((object.ReferenceEquals(this.业务范围Field, value) != true)) {
                    this.业务范围Field = value;
                    this.RaisePropertyChanged("业务范围");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 传真 {
            get {
                return this.传真Field;
            }
            set {
                if ((object.ReferenceEquals(this.传真Field, value) != true)) {
                    this.传真Field = value;
                    this.RaisePropertyChanged("传真");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 供应商名称 {
            get {
                return this.供应商名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.供应商名称Field, value) != true)) {
                    this.供应商名称Field = value;
                    this.RaisePropertyChanged("供应商名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 供应商编码 {
            get {
                return this.供应商编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.供应商编码Field, value) != true)) {
                    this.供应商编码Field = value;
                    this.RaisePropertyChanged("供应商编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 地址 {
            get {
                return this.地址Field;
            }
            set {
                if ((object.ReferenceEquals(this.地址Field, value) != true)) {
                    this.地址Field = value;
                    this.RaisePropertyChanged("地址");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注 {
            get {
                return this.备注Field;
            }
            set {
                if ((object.ReferenceEquals(this.备注Field, value) != true)) {
                    this.备注Field = value;
                    this.RaisePropertyChanged("备注");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 开户银行 {
            get {
                return this.开户银行Field;
            }
            set {
                if ((object.ReferenceEquals(this.开户银行Field, value) != true)) {
                    this.开户银行Field = value;
                    this.RaisePropertyChanged("开户银行");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 电话 {
            get {
                return this.电话Field;
            }
            set {
                if ((object.ReferenceEquals(this.电话Field, value) != true)) {
                    this.电话Field = value;
                    this.RaisePropertyChanged("电话");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 联系人 {
            get {
                return this.联系人Field;
            }
            set {
                if ((object.ReferenceEquals(this.联系人Field, value) != true)) {
                    this.联系人Field = value;
                    this.RaisePropertyChanged("联系人");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 联系人手机 {
            get {
                return this.联系人手机Field;
            }
            set {
                if ((object.ReferenceEquals(this.联系人手机Field, value) != true)) {
                    this.联系人手机Field = value;
                    this.RaisePropertyChanged("联系人手机");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 邮编 {
            get {
                return this.邮编Field;
            }
            set {
                if ((object.ReferenceEquals(this.邮编Field, value) != true)) {
                    this.邮编Field = value;
                    this.RaisePropertyChanged("邮编");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 银行账号 {
            get {
                return this.银行账号Field;
            }
            set {
                if ((object.ReferenceEquals(this.银行账号Field, value) != true)) {
                    this.银行账号Field = value;
                    this.RaisePropertyChanged("银行账号");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_会计期间", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_会计期间 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 会计期间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 会计期间_BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 会计期间_EField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 年份Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库编码 {
            get {
                return this.仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库编码Field, value) != true)) {
                    this.仓库编码Field = value;
                    this.RaisePropertyChanged("仓库编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 会计期间 {
            get {
                return this.会计期间Field;
            }
            set {
                if ((object.ReferenceEquals(this.会计期间Field, value) != true)) {
                    this.会计期间Field = value;
                    this.RaisePropertyChanged("会计期间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 会计期间_B {
            get {
                return this.会计期间_BField;
            }
            set {
                if ((this.会计期间_BField.Equals(value) != true)) {
                    this.会计期间_BField = value;
                    this.RaisePropertyChanged("会计期间_B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 会计期间_E {
            get {
                return this.会计期间_EField;
            }
            set {
                if ((this.会计期间_EField.Equals(value) != true)) {
                    this.会计期间_EField = value;
                    this.RaisePropertyChanged("会计期间_E");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 年份 {
            get {
                return this.年份Field;
            }
            set {
                if ((object.ReferenceEquals(this.年份Field, value) != true)) {
                    this.年份Field = value;
                    this.RaisePropertyChanged("年份");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_库存分布", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_库存分布 : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 仓库编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool 包含下级Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 存货名称Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 类别编码Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 仓库编码 {
            get {
                return this.仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.仓库编码Field, value) != true)) {
                    this.仓库编码Field = value;
                    this.RaisePropertyChanged("仓库编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool 包含下级 {
            get {
                return this.包含下级Field;
            }
            set {
                if ((this.包含下级Field.Equals(value) != true)) {
                    this.包含下级Field = value;
                    this.RaisePropertyChanged("包含下级");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 存货名称 {
            get {
                return this.存货名称Field;
            }
            set {
                if ((object.ReferenceEquals(this.存货名称Field, value) != true)) {
                    this.存货名称Field = value;
                    this.RaisePropertyChanged("存货名称");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 类别编码 {
            get {
                return this.类别编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.类别编码Field, value) != true)) {
                    this.类别编码Field = value;
                    this.RaisePropertyChanged("类别编码");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataType_User", Namespace="http://schemas.datacontract.org/2004/07/STK_Service")]
    [System.SerializableAttribute()]
    public partial class DataType_User : STK_Client.Ref_WS_STK.ModelBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginAddrField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LoginDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LoginIDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginPswdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MobiPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewUserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NewUserPswdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RoleListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserEmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserPswdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 入职时间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 可入仓库编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 可出仓库编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 备注Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 家庭住址Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 工作岗位Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 所在店铺编码Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime 离职时间Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 职务Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string 身份证号Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginAddr {
            get {
                return this.LoginAddrField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginAddrField, value) != true)) {
                    this.LoginAddrField = value;
                    this.RaisePropertyChanged("LoginAddr");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LoginDate {
            get {
                return this.LoginDateField;
            }
            set {
                if ((this.LoginDateField.Equals(value) != true)) {
                    this.LoginDateField = value;
                    this.RaisePropertyChanged("LoginDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LoginID {
            get {
                return this.LoginIDField;
            }
            set {
                if ((this.LoginIDField.Equals(value) != true)) {
                    this.LoginIDField = value;
                    this.RaisePropertyChanged("LoginID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginName {
            get {
                return this.LoginNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginNameField, value) != true)) {
                    this.LoginNameField = value;
                    this.RaisePropertyChanged("LoginName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LoginPswd {
            get {
                return this.LoginPswdField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginPswdField, value) != true)) {
                    this.LoginPswdField = value;
                    this.RaisePropertyChanged("LoginPswd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobiPhone {
            get {
                return this.MobiPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.MobiPhoneField, value) != true)) {
                    this.MobiPhoneField = value;
                    this.RaisePropertyChanged("MobiPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewUserCode {
            get {
                return this.NewUserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.NewUserCodeField, value) != true)) {
                    this.NewUserCodeField = value;
                    this.RaisePropertyChanged("NewUserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NewUserPswd {
            get {
                return this.NewUserPswdField;
            }
            set {
                if ((object.ReferenceEquals(this.NewUserPswdField, value) != true)) {
                    this.NewUserPswdField = value;
                    this.RaisePropertyChanged("NewUserPswd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RoleList {
            get {
                return this.RoleListField;
            }
            set {
                if ((object.ReferenceEquals(this.RoleListField, value) != true)) {
                    this.RoleListField = value;
                    this.RaisePropertyChanged("RoleList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode {
            get {
                return this.UserCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.UserCodeField, value) != true)) {
                    this.UserCodeField = value;
                    this.RaisePropertyChanged("UserCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserEmail {
            get {
                return this.UserEmailField;
            }
            set {
                if ((object.ReferenceEquals(this.UserEmailField, value) != true)) {
                    this.UserEmailField = value;
                    this.RaisePropertyChanged("UserEmail");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserPswd {
            get {
                return this.UserPswdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserPswdField, value) != true)) {
                    this.UserPswdField = value;
                    this.RaisePropertyChanged("UserPswd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserState {
            get {
                return this.UserStateField;
            }
            set {
                if ((this.UserStateField.Equals(value) != true)) {
                    this.UserStateField = value;
                    this.RaisePropertyChanged("UserState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkName {
            get {
                return this.WorkNameField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkNameField, value) != true)) {
                    this.WorkNameField = value;
                    this.RaisePropertyChanged("WorkName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkPhone {
            get {
                return this.WorkPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkPhoneField, value) != true)) {
                    this.WorkPhoneField = value;
                    this.RaisePropertyChanged("WorkPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 入职时间 {
            get {
                return this.入职时间Field;
            }
            set {
                if ((this.入职时间Field.Equals(value) != true)) {
                    this.入职时间Field = value;
                    this.RaisePropertyChanged("入职时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 可入仓库编码 {
            get {
                return this.可入仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.可入仓库编码Field, value) != true)) {
                    this.可入仓库编码Field = value;
                    this.RaisePropertyChanged("可入仓库编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 可出仓库编码 {
            get {
                return this.可出仓库编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.可出仓库编码Field, value) != true)) {
                    this.可出仓库编码Field = value;
                    this.RaisePropertyChanged("可出仓库编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 备注 {
            get {
                return this.备注Field;
            }
            set {
                if ((object.ReferenceEquals(this.备注Field, value) != true)) {
                    this.备注Field = value;
                    this.RaisePropertyChanged("备注");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 家庭住址 {
            get {
                return this.家庭住址Field;
            }
            set {
                if ((object.ReferenceEquals(this.家庭住址Field, value) != true)) {
                    this.家庭住址Field = value;
                    this.RaisePropertyChanged("家庭住址");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 工作岗位 {
            get {
                return this.工作岗位Field;
            }
            set {
                if ((object.ReferenceEquals(this.工作岗位Field, value) != true)) {
                    this.工作岗位Field = value;
                    this.RaisePropertyChanged("工作岗位");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 所在店铺编码 {
            get {
                return this.所在店铺编码Field;
            }
            set {
                if ((object.ReferenceEquals(this.所在店铺编码Field, value) != true)) {
                    this.所在店铺编码Field = value;
                    this.RaisePropertyChanged("所在店铺编码");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime 离职时间 {
            get {
                return this.离职时间Field;
            }
            set {
                if ((this.离职时间Field.Equals(value) != true)) {
                    this.离职时间Field = value;
                    this.RaisePropertyChanged("离职时间");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 职务 {
            get {
                return this.职务Field;
            }
            set {
                if ((object.ReferenceEquals(this.职务Field, value) != true)) {
                    this.职务Field = value;
                    this.RaisePropertyChanged("职务");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string 身份证号 {
            get {
                return this.身份证号Field;
            }
            set {
                if ((object.ReferenceEquals(this.身份证号Field, value) != true)) {
                    this.身份证号Field = value;
                    this.RaisePropertyChanged("身份证号");
                }
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Ref_WS_STK.IWS_STK")]
    public interface IWS_STK {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Test", ReplyAction="http://tempuri.org/IWS_STK/SYS_TestResponse")]
        string SYS_Test(string ATestName);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Login", ReplyAction="http://tempuri.org/IWS_STK/SYS_LoginResponse")]
        void SYS_Login(ref STK_Client.Ref_WS_STK.DataType_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Login_Menu", ReplyAction="http://tempuri.org/IWS_STK/SYS_Login_MenuResponse")]
        System.Data.DataSet SYS_Login_Menu(ref STK_Client.Ref_WS_STK.DataType_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Logout", ReplyAction="http://tempuri.org/IWS_STK/SYS_LogoutResponse")]
        void SYS_Logout(STK_Client.Ref_WS_STK.DataType_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/Sys_User_List", ReplyAction="http://tempuri.org/IWS_STK/Sys_User_ListResponse")]
        System.Data.DataSet Sys_User_List(STK_Client.Ref_WS_STK.DataType_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/Sys_User_Edit", ReplyAction="http://tempuri.org/IWS_STK/Sys_User_EditResponse")]
        void Sys_User_Edit(ref STK_Client.Ref_WS_STK.DataType_User model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/Sys_Role_List", ReplyAction="http://tempuri.org/IWS_STK/Sys_Role_ListResponse")]
        System.Data.DataSet Sys_Role_List(STK_Client.Ref_WS_STK.DataType_Role model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/Sys_Role_Edit", ReplyAction="http://tempuri.org/IWS_STK/Sys_Role_EditResponse")]
        void Sys_Role_Edit(ref STK_Client.Ref_WS_STK.DataType_Role model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/Sys_Menu_List", ReplyAction="http://tempuri.org/IWS_STK/Sys_Menu_ListResponse")]
        System.Data.DataSet Sys_Menu_List(int ARoleID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Param_Get", ReplyAction="http://tempuri.org/IWS_STK/SYS_Param_GetResponse")]
        void SYS_Param_Get(ref STK_Client.Ref_WS_STK.DataType_Param model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Param_Set", ReplyAction="http://tempuri.org/IWS_STK/SYS_Param_SetResponse")]
        void SYS_Param_Set(ref STK_Client.Ref_WS_STK.DataType_Param model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Grid_Get", ReplyAction="http://tempuri.org/IWS_STK/SYS_Grid_GetResponse")]
        void SYS_Grid_Get(ref STK_Client.Ref_WS_STK.DataType_Grid model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/SYS_Grid_Set", ReplyAction="http://tempuri.org/IWS_STK/SYS_Grid_SetResponse")]
        void SYS_Grid_Set(ref STK_Client.Ref_WS_STK.DataType_Grid model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/GetTableDef", ReplyAction="http://tempuri.org/IWS_STK/GetTableDefResponse")]
        string GetTableDef(string tableid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_储物箱_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_储物箱_ListResponse")]
        System.Data.DataSet BAS_储物箱_List(STK_Client.Ref_WS_STK.DataType_仓库 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_储物箱_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_储物箱_EditResponse")]
        void BAS_储物箱_Edit(ref STK_Client.Ref_WS_STK.DataType_仓库 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_货架_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_货架_ListResponse")]
        System.Data.DataSet BAS_货架_List(STK_Client.Ref_WS_STK.DataType_仓库 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_货架_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_货架_EditResponse")]
        void BAS_货架_Edit(ref STK_Client.Ref_WS_STK.DataType_仓库 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_仓库_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_仓库_ListResponse")]
        System.Data.DataSet BAS_仓库_List(STK_Client.Ref_WS_STK.DataType_仓库 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_仓库_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_仓库_EditResponse")]
        void BAS_仓库_Edit(ref STK_Client.Ref_WS_STK.DataType_仓库 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_仓库_类型_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_仓库_类型_ListResponse")]
        System.Data.DataSet BAS_仓库_类型_List();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_存货_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_存货_ListResponse")]
        System.Data.DataSet BAS_存货_List(STK_Client.Ref_WS_STK.DataType_存货 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_存货_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_存货_EditResponse")]
        void BAS_存货_Edit(ref STK_Client.Ref_WS_STK.DataType_存货 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_存货_类别_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_存货_类别_ListResponse")]
        System.Data.DataSet BAS_存货_类别_List(STK_Client.Ref_WS_STK.DataType_存货_类别 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_存货_类别_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_存货_类别_EditResponse")]
        void BAS_存货_类别_Edit(ref STK_Client.Ref_WS_STK.DataType_存货_类别 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_存货_类别_Down", ReplyAction="http://tempuri.org/IWS_STK/BAS_存货_类别_DownResponse")]
        System.Data.DataSet BAS_存货_类别_Down(ref STK_Client.Ref_WS_STK.DataType_存货_类别 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_期初库存_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_期初库存_ListResponse")]
        System.Data.DataSet BAS_期初库存_List(STK_Client.Ref_WS_STK.DataType_库存管理 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_期初库存_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_期初库存_EditResponse")]
        void BAS_期初库存_Edit(ref STK_Client.Ref_WS_STK.DataType_库存管理 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_供应商_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_供应商_ListResponse")]
        System.Data.DataSet BAS_供应商_List(STK_Client.Ref_WS_STK.DataType_供应商 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_供应商_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_供应商_EditResponse")]
        void BAS_供应商_Edit(ref STK_Client.Ref_WS_STK.DataType_供应商 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/STK_库存出库_List", ReplyAction="http://tempuri.org/IWS_STK/STK_库存出库_ListResponse")]
        System.Data.DataSet STK_库存出库_List(STK_Client.Ref_WS_STK.DataType_库存管理 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/STK_库存出库_Edit", ReplyAction="http://tempuri.org/IWS_STK/STK_库存出库_EditResponse")]
        void STK_库存出库_Edit(ref STK_Client.Ref_WS_STK.DataType_库存管理 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/STK_库存入库_List", ReplyAction="http://tempuri.org/IWS_STK/STK_库存入库_ListResponse")]
        System.Data.DataSet STK_库存入库_List(STK_Client.Ref_WS_STK.DataType_库存管理 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/STK_库存入库_Edit", ReplyAction="http://tempuri.org/IWS_STK/STK_库存入库_EditResponse")]
        void STK_库存入库_Edit(ref STK_Client.Ref_WS_STK.DataType_库存管理 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_会计期间_List", ReplyAction="http://tempuri.org/IWS_STK/BAS_会计期间_ListResponse")]
        System.Data.DataSet BAS_会计期间_List(STK_Client.Ref_WS_STK.DataType_会计期间 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/BAS_会计期间_Edit", ReplyAction="http://tempuri.org/IWS_STK/BAS_会计期间_EditResponse")]
        void BAS_会计期间_Edit(ref STK_Client.Ref_WS_STK.DataType_会计期间 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/STK_库存分布_List", ReplyAction="http://tempuri.org/IWS_STK/STK_库存分布_ListResponse")]
        System.Data.DataSet STK_库存分布_List(STK_Client.Ref_WS_STK.DataType_库存分布 model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWS_STK/STK_库存总账_List", ReplyAction="http://tempuri.org/IWS_STK/STK_库存总账_ListResponse")]
        System.Data.DataSet STK_库存总账_List(STK_Client.Ref_WS_STK.DataType_库存管理 model);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWS_STKChannel : STK_Client.Ref_WS_STK.IWS_STK, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_STKClient : System.ServiceModel.ClientBase<STK_Client.Ref_WS_STK.IWS_STK>, STK_Client.Ref_WS_STK.IWS_STK {
        
        public WS_STKClient() {
        }
        
        public WS_STKClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_STKClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_STKClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_STKClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string SYS_Test(string ATestName) {
            return base.Channel.SYS_Test(ATestName);
        }
        
        public void SYS_Login(ref STK_Client.Ref_WS_STK.DataType_User model) {
            base.Channel.SYS_Login(ref model);
        }
        
        public System.Data.DataSet SYS_Login_Menu(ref STK_Client.Ref_WS_STK.DataType_User model) {
            return base.Channel.SYS_Login_Menu(ref model);
        }
        
        public void SYS_Logout(STK_Client.Ref_WS_STK.DataType_User model) {
            base.Channel.SYS_Logout(model);
        }
        
        public System.Data.DataSet Sys_User_List(STK_Client.Ref_WS_STK.DataType_User model) {
            return base.Channel.Sys_User_List(model);
        }
        
        public void Sys_User_Edit(ref STK_Client.Ref_WS_STK.DataType_User model) {
            base.Channel.Sys_User_Edit(ref model);
        }
        
        public System.Data.DataSet Sys_Role_List(STK_Client.Ref_WS_STK.DataType_Role model) {
            return base.Channel.Sys_Role_List(model);
        }
        
        public void Sys_Role_Edit(ref STK_Client.Ref_WS_STK.DataType_Role model) {
            base.Channel.Sys_Role_Edit(ref model);
        }
        
        public System.Data.DataSet Sys_Menu_List(int ARoleID) {
            return base.Channel.Sys_Menu_List(ARoleID);
        }
        
        public void SYS_Param_Get(ref STK_Client.Ref_WS_STK.DataType_Param model) {
            base.Channel.SYS_Param_Get(ref model);
        }
        
        public void SYS_Param_Set(ref STK_Client.Ref_WS_STK.DataType_Param model) {
            base.Channel.SYS_Param_Set(ref model);
        }
        
        public void SYS_Grid_Get(ref STK_Client.Ref_WS_STK.DataType_Grid model) {
            base.Channel.SYS_Grid_Get(ref model);
        }
        
        public void SYS_Grid_Set(ref STK_Client.Ref_WS_STK.DataType_Grid model) {
            base.Channel.SYS_Grid_Set(ref model);
        }
        
        public string GetTableDef(string tableid) {
            return base.Channel.GetTableDef(tableid);
        }
        
        public System.Data.DataSet BAS_储物箱_List(STK_Client.Ref_WS_STK.DataType_仓库 model) {
            return base.Channel.BAS_储物箱_List(model);
        }
        
        public void BAS_储物箱_Edit(ref STK_Client.Ref_WS_STK.DataType_仓库 model) {
            base.Channel.BAS_储物箱_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_货架_List(STK_Client.Ref_WS_STK.DataType_仓库 model) {
            return base.Channel.BAS_货架_List(model);
        }
        
        public void BAS_货架_Edit(ref STK_Client.Ref_WS_STK.DataType_仓库 model) {
            base.Channel.BAS_货架_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_仓库_List(STK_Client.Ref_WS_STK.DataType_仓库 model) {
            return base.Channel.BAS_仓库_List(model);
        }
        
        public void BAS_仓库_Edit(ref STK_Client.Ref_WS_STK.DataType_仓库 model) {
            base.Channel.BAS_仓库_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_仓库_类型_List() {
            return base.Channel.BAS_仓库_类型_List();
        }
        
        public System.Data.DataSet BAS_存货_List(STK_Client.Ref_WS_STK.DataType_存货 model) {
            return base.Channel.BAS_存货_List(model);
        }
        
        public void BAS_存货_Edit(ref STK_Client.Ref_WS_STK.DataType_存货 model) {
            base.Channel.BAS_存货_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_存货_类别_List(STK_Client.Ref_WS_STK.DataType_存货_类别 model) {
            return base.Channel.BAS_存货_类别_List(model);
        }
        
        public void BAS_存货_类别_Edit(ref STK_Client.Ref_WS_STK.DataType_存货_类别 model) {
            base.Channel.BAS_存货_类别_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_存货_类别_Down(ref STK_Client.Ref_WS_STK.DataType_存货_类别 model) {
            return base.Channel.BAS_存货_类别_Down(ref model);
        }
        
        public System.Data.DataSet BAS_期初库存_List(STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            return base.Channel.BAS_期初库存_List(model);
        }
        
        public void BAS_期初库存_Edit(ref STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            base.Channel.BAS_期初库存_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_供应商_List(STK_Client.Ref_WS_STK.DataType_供应商 model) {
            return base.Channel.BAS_供应商_List(model);
        }
        
        public void BAS_供应商_Edit(ref STK_Client.Ref_WS_STK.DataType_供应商 model) {
            base.Channel.BAS_供应商_Edit(ref model);
        }
        
        public System.Data.DataSet STK_库存出库_List(STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            return base.Channel.STK_库存出库_List(model);
        }
        
        public void STK_库存出库_Edit(ref STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            base.Channel.STK_库存出库_Edit(ref model);
        }
        
        public System.Data.DataSet STK_库存入库_List(STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            return base.Channel.STK_库存入库_List(model);
        }
        
        public void STK_库存入库_Edit(ref STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            base.Channel.STK_库存入库_Edit(ref model);
        }
        
        public System.Data.DataSet BAS_会计期间_List(STK_Client.Ref_WS_STK.DataType_会计期间 model) {
            return base.Channel.BAS_会计期间_List(model);
        }
        
        public void BAS_会计期间_Edit(ref STK_Client.Ref_WS_STK.DataType_会计期间 model) {
            base.Channel.BAS_会计期间_Edit(ref model);
        }
        
        public System.Data.DataSet STK_库存分布_List(STK_Client.Ref_WS_STK.DataType_库存分布 model) {
            return base.Channel.STK_库存分布_List(model);
        }
        
        public System.Data.DataSet STK_库存总账_List(STK_Client.Ref_WS_STK.DataType_库存管理 model) {
            return base.Channel.STK_库存总账_List(model);
        }
    }
}
